### ISSUE TITLE
Create Roadmap w/ Epics

### ISSUE THREAD

**Issue by ezronis** [TheWITProject/CentershipApp#3]
**Acceptance Criteria:** As a Product Manager, I want to empower my team with a roadmap so that they can accomplish all the goals they set to achieve by the end of the 3rd sprint. 

**Definition of Done**
- [ ] identified which epics will be accomplished by the end of the program
- [ ] create a rough draft of a roadmap driven by those milestones
- [ ] outlined epics for the next 2 sprints in detail
- [ ] get sign off on roadmap from tech lead & team
- [ ] review roadmap at the end of each sprint
